name: Deploy Site to S3 in Test

on:
  push:
    branches:
      - main

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  S3PackageUpload:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::381492093988:role/GithubActions-WebIdentity-Role
          role-session-name: githubactionsession
          aws-region: ${{ vars.AWS_REGION }}
          
      - name:  Copy index.html to s3
        run: aws s3 sync ./test/site s3://${{ vars.TEST_SITE_BUCKET_NAME }}/

  InvalidateCloudFront:
    needs: S3PackageUpload
    runs-on: ubuntu-latest
    steps:
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::339713009188:role/GithubActions-WebIdentity-Role
          role-session-name: githubactionsession
          aws-region: ${{ vars.AWS_REGION }}

      - name: invalidateCloudFront
        run: aws cloudfront create-invalidation --distribution-id ${{ vars.TEST_DISTRIBUTION_ID }} --paths '/*'
